// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:s01_day3_am_project/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BookingAdapter());
    registerAdapter(EventAdapter());
    registerAdapter(PackageAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BookingAdapter());
    registerAdapter(EventAdapter());
    registerAdapter(PackageAdapter());
  }
}
